"""initial schema - 12 tables

Revision ID: 2400a4b28abc
Revises: 
Create Date: 2026-04-11 17:44:03.983606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2400a4b28abc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_class', sa.Enum('ACTION_US', 'ACTION_EU', 'ETF', 'CRYPTO', 'FOREX', 'COMMODITY', name='assetclass'), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=True)
    op.create_table('performance_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('equity', sa.Float(), nullable=False),
    sa.Column('daily_pnl', sa.Float(), nullable=True),
    sa.Column('daily_return', sa.Float(), nullable=True),
    sa.Column('cumulative_return', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('meta_score', sa.Float(), nullable=True),
    sa.Column('portfolio_regime', sa.Enum('ALPHA', 'BETA', 'STRESS', name='portfolioregime'), nullable=True),
    sa.Column('ews_level', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', name='uq_performance_daily_date')
    )
    op.create_index(op.f('ix_performance_daily_date'), 'performance_daily', ['date'], unique=False)
    op.create_table('asset_genome',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('cycle_phase', sa.Integer(), nullable=True),
    sa.Column('seismograph', sa.JSON(), nullable=True),
    sa.Column('fractal_memory', sa.JSON(), nullable=True),
    sa.Column('contagion_network', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id')
    )
    op.create_table('features_daily',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sma_20', sa.Float(), nullable=True),
    sa.Column('sma_50', sa.Float(), nullable=True),
    sa.Column('sma_200', sa.Float(), nullable=True),
    sa.Column('ema_12', sa.Float(), nullable=True),
    sa.Column('ema_26', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('macd_histogram', sa.Float(), nullable=True),
    sa.Column('bollinger_upper', sa.Float(), nullable=True),
    sa.Column('bollinger_middle', sa.Float(), nullable=True),
    sa.Column('bollinger_lower', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.Column('stochastic_k', sa.Float(), nullable=True),
    sa.Column('stochastic_d', sa.Float(), nullable=True),
    sa.Column('score_correlation', sa.Float(), nullable=True),
    sa.Column('score_sentiment', sa.Float(), nullable=True),
    sa.Column('score_technical', sa.Float(), nullable=True),
    sa.Column('score_genome', sa.Float(), nullable=True),
    sa.Column('score_ipi', sa.Float(), nullable=True),
    sa.Column('score_ivf', sa.Float(), nullable=True),
    sa.Column('score_mts', sa.Float(), nullable=True),
    sa.Column('score_sgi', sa.Float(), nullable=True),
    sa.Column('score_sus', sa.Float(), nullable=True),
    sa.Column('score_final', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', name='uq_features_daily_asset_date')
    )
    op.create_index(op.f('ix_features_daily_date'), 'features_daily', ['date'], unique=False)
    op.create_table('ohlcv_1h',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'datetime', name='uq_ohlcv_1h_asset_dt')
    )
    op.create_index(op.f('ix_ohlcv_1h_datetime'), 'ohlcv_1h', ['datetime'], unique=False)
    op.create_table('ohlcv_5min',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'datetime', name='uq_ohlcv_5min_asset_dt')
    )
    op.create_index(op.f('ix_ohlcv_5min_datetime'), 'ohlcv_5min', ['datetime'], unique=False)
    op.create_table('ohlcv_daily',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', name='uq_ohlcv_daily_asset_date')
    )
    op.create_index('ix_ohlcv_daily_date', 'ohlcv_daily', ['date'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', 'NEUTRAL', name='signaldirection'), nullable=False),
    sa.Column('entry_price', sa.Float(), nullable=False),
    sa.Column('exit_price', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', name='positionstatus'), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('pnl_percent', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('attribution', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.Enum('LONG', 'SHORT', 'NEUTRAL', name='signaldirection'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('context_quality', sa.Float(), nullable=True),
    sa.Column('shelf_life_minutes', sa.Integer(), nullable=True),
    sa.Column('entry_price', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('take_profit_1', sa.Float(), nullable=True),
    sa.Column('take_profit_2', sa.Float(), nullable=True),
    sa.Column('risk_reward_ratio', sa.Float(), nullable=True),
    sa.Column('kelly_size', sa.Float(), nullable=True),
    sa.Column('strategy_name', sa.String(length=100), nullable=True),
    sa.Column('regime', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('signal_id', sa.Integer(), nullable=True),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.Enum('BUY', 'SELL', name='orderside'), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('filled_price', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PARTIAL', 'FILLED', 'CANCELLED', name='orderstatus'), nullable=True),
    sa.Column('tranche', sa.Integer(), nullable=True),
    sa.Column('broker', sa.String(length=50), nullable=True),
    sa.Column('broker_order_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    op.drop_table('signals')
    op.drop_table('positions')
    op.drop_index('ix_ohlcv_daily_date', table_name='ohlcv_daily')
    op.drop_table('ohlcv_daily')
    op.drop_index(op.f('ix_ohlcv_5min_datetime'), table_name='ohlcv_5min')
    op.drop_table('ohlcv_5min')
    op.drop_index(op.f('ix_ohlcv_1h_datetime'), table_name='ohlcv_1h')
    op.drop_table('ohlcv_1h')
    op.drop_index(op.f('ix_features_daily_date'), table_name='features_daily')
    op.drop_table('features_daily')
    op.drop_table('asset_genome')
    op.drop_index(op.f('ix_performance_daily_date'), table_name='performance_daily')
    op.drop_table('performance_daily')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
